### PR TITLE
Add Matano backend

### PR DESCRIPTION
**Pull request by Samrose-Ahmed**
Hello, I have created a backend for [Matano](https://www.matano.dev) to convert Sigma rules into [Matano Python detections](https://www.matano.dev/docs/detections).

Backend: https://github.com/matanolabs/pySigma-backend-matano

I believe I need to create a PR so users can use the backend with the sigma cli as I couldn't find a way to load the backend otherwise. I tried to follow the guidelines in the README, let me know if anything is missing.

### CODE REVIEW

**Comment by Samrose-Ahmed** [comment]
I believe poetry==1.1 is broken, I tried to install it locally (Ubuntu) from pip and got the same error as in the CI (seems to be a dependency issue). I upgraded the build to use 1.1.15 (latest 1.1.x) which works. I tested locally and tests pass.

**Comment by thomaspatzke** [comment]
Cool! I will review and merge as soon I find some time.

**Comment by thomaspatzke** [comment]
See my review comment regarding the PyPI release, everything else is fine.

Can you upgrade to the latest version of pySigma? I plan to lift the CLI to the latest version soon to add some new features. This requires that all backend upgrade to the new version (second digit of the version number), too.

**Comment by Samrose-Ahmed** [comment]
Thanks, I don't see your review comment, did you perhaps forget to post it? I updated the backend to use pySigma ^0.8.1.

**Comment by thomaspatzke** [comment]
It's regarding pyproject.toml:

> This will prevent packaging and a PyPI release. Can you please release to PyPI and reference the package from here, similar to the backends above?

**Comment by thomaspatzke** [comment]
Please merge from or rebase to the current main branch. Poetry was updated and broke the CI testing.

**Comment by thomaspatzke** [comment]
As announced [here](https://github.com/SigmaHQ/sigma-cli/issues/3) Sigma CLI will be switched to a plugin architecture, which means that backends will be installable on demand. I think this will also allow that backends are installed from Git repositories. Therefore this PR and likely also the PyPI release get obsolete soon, at least for the CLI integration. I recommend to make a PyPI release anyways, because this increases accessibility for developers that want to integrate the backend in their own tooling.

**Comment by Samrose-Ahmed** [comment]
Awesome, Thomas, thanks that sounds great! I'll close this PR then.

**Pull request closed without merging**
